### ISSUE TITLE
ExtractMentions does not Extract mentions with point

### ISSUE THREAD

**Issue by herhu** [srinathh/hashtag#2]
Hi, the function `ExtractMentions` only return the first word of the mention with point.

ej: 

`var mention = "hi.bro"`
 `mention = ExtractMentions(mention)`
`fmt.println(mention) //hi`

How we can solve?

**Comment by herhu** [comment]
this work:

`var validMention = regexp.MustCompile("([^A-Za-z0-9_.!#$%&*" + atSignsChars + "]|^|[Rr][tT]:?)(" + atSigns + "+)([A-Za-z0-9_.]{1,20})")`

**Comment by srinathh** [comment]
Looks cool. Want to send a pull request?
